# -*- coding: utf-8 -*-
"""
Created on Fri Jun 19 22:20:26 2026
@author: ammar

UPDATED DIAGNOSTIC: Compare Python Q3 vs Original Malone R Q3 Outputs
Run this separately after the Q3 workflow completes

This now checks:
1. All CSV outputs (including threshold and response files)
2. All figure outputs
3. Key numeric columns in each table
4. Row counts and file existence

FIXED: threshold_pct is now included as a merge key for threshold tables
"""

import os
import pandas as pd
import numpy as np
from pathlib import Path

# ============================================================================
# PATHS - UPDATED TO MATCH NEW WORKFLOW
# ============================================================================

python_output_dir = r"M:\Research\WUE_CUE\WUE_manuscript_version6\Q3\results\Q3_WUE_T_SPEI_sensitivity"
python_figure_dir = r"M:\Research\WUE_CUE\WUE_manuscript_version6\Q3\figures"
malone_output_dir = r"M:\Research\WUE_CUE\Water_WUE\Malone_Workflow\results\Q3_WUE_T_SPEI_sensitivity"

print("="*70)
print("UPDATED DIAGNOSTIC: COMPARING PYTHON Q3 vs MALONE R Q3 OUTPUTS")
print("="*70)

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def normalize_threshold_pct(df):
    """Normalize threshold_pct column to consistent string format"""
    if 'threshold_pct' in df.columns:
        # Convert to string, remove .0 if present
        df['threshold_pct'] = df['threshold_pct'].astype(str).str.replace('.0', '', regex=False)
        # Add % if missing
        df['threshold_pct'] = df['threshold_pct'].apply(
            lambda x: x if x.endswith('%') else x + '%'
        )
    return df

def compare_dataframes(df1, df2, name, merge_cols, compare_cols, tolerance=0.01):
    """Compare two dataframes on specified columns"""
    print(f"\n  {name}:")
    print(f"    Python: {len(df1)} rows")
    print(f"    Malone: {len(df2)} rows")
    
    # Check if merge columns exist
    missing_py = [col for col in merge_cols if col not in df1.columns]
    missing_ml = [col for col in merge_cols if col not in df2.columns]
    if missing_py or missing_ml:
        print(f"    WARNING: Missing merge columns - Python: {missing_py}, Malone: {missing_ml}")
        return {}, False
    
    # Try to merge
    try:
        merged = df1.merge(df2, on=merge_cols, suffixes=('_python', '_malone'), how='inner')
    except Exception as e:
        print(f"    ERROR merging: {e}")
        return {}, False
    
    if len(merged) == 0:
        print("    WARNING: No matching rows found")
        print(f"    Merge columns: {merge_cols}")
        return {}, False
    
    print(f"    Merged rows: {len(merged)}")
    
    results = {}
    all_match = True
    
    for col in compare_cols:
        py_col = f'{col}_python'
        ml_col = f'{col}_malone'
        if py_col in merged.columns and ml_col in merged.columns:
            # Handle numeric columns only
            if pd.api.types.is_numeric_dtype(merged[py_col]) and pd.api.types.is_numeric_dtype(merged[ml_col]):
                diff = np.abs(merged[py_col] - merged[ml_col])
                max_diff = diff.max()
                nan_count = diff.isna().sum()
                results[col] = max_diff
                
                if nan_count > 0 and nan_count < len(merged):
                    print(f"    {col}: {nan_count} NaN values in difference")
                elif max_diff <= 0.00001:
                    print(f"    {col}: Max diff = {max_diff:.8f} [IDENTICAL]")
                elif max_diff <= tolerance:
                    print(f"    {col}: Max diff = {max_diff:.8f} [OK]")
                else:
                    all_match = False
                    print(f"    {col}: Max diff = {max_diff:.8f} [FAIL]")
            else:
                # Non-numeric: check if values are identical
                matches = (merged[py_col] == merged[ml_col]).all()
                if matches:
                    print(f"    {col}: [IDENTICAL]")
                else:
                    all_match = False
                    print(f"    {col}: [FAIL] - values differ")
        else:
            print(f"    {col}: Column not found in one or both dataframes")
    
    return results, all_match

# ============================================================================
# FILE LISTS - FULL SET
# ============================================================================

print("\n" + "-"*70)
print("STEP 1: Checking all output files exist")
print("-"*70)

# All CSV files generated by Q3 workflow
all_csv_files = {
    # Core data files
    "model_base": "Q3_WUE_T_SPEI_model_base_wide.csv",
    "model_data": "Q3_WUE_T_SPEI_model_data_long.csv",
    "coverage": "Q3_WUE_T_SPEI_coverage.csv",
    
    # Site-level files
    "site_slopes": "Q3_WUE_T_SPEI_site_level_slopes.csv",
    "site_near_normal_baselines": "Q3_WUE_T_SPEI_site_near_normal_baselines.csv",
    "site_response_data": "Q3_WUE_T_SPEI_site_response_from_near_normal.csv",
    "site_sensitivity_rank": "Q3_WUE_T_SPEI_site_sensitivity_rank.csv",
    
    # Summary files
    "ecosystem_slope_summary": "Q3_WUE_T_SPEI_ecosystem_slope_summary.csv",
    "coast_slope_summary": "Q3_WUE_T_SPEI_coast_region_slope_summary.csv",
    "coastline_sensitivity_summary": "Q3_WUE_T_SPEI_coastline_grouped_site_sensitivity_summary.csv",
    
    # Model files
    "model_comparison": "Q3_WUE_T_SPEI_model_comparison.csv",
    "smooth_terms": "Q3_WUE_T_SPEI_smooth_terms.csv",
    "parametric_terms": "Q3_WUE_T_SPEI_smooth_parametric_terms.csv",
    "coast_smooth_terms": "Q3_WUE_T_SPEI_coast_threshold_GAM_smooth_terms.csv",
    "coast_parametric_terms": "Q3_WUE_T_SPEI_coast_threshold_GAM_parametric_terms.csv",
    
    # Prediction files
    "predictions": "Q3_WUE_T_SPEI_smooth_predictions.csv",
    "coast_predictions": "Q3_WUE_T_SPEI_coast_threshold_GAM_predictions_upland.csv",
    
    # Impact and threshold files
    "predicted_near_normal_baselines": "Q3_WUE_T_SPEI_predicted_near_normal_baselines.csv",
    "predicted_impact_classes": "Q3_WUE_T_SPEI_predicted_impact_classes.csv",
    "predicted_impact_thresholds": "Q3_WUE_T_SPEI_predicted_impact_thresholds_10pct.csv",
    
    "coast_near_normal_baselines": "Q3_WUE_T_SPEI_coast_threshold_GAM_near_normal_baselines_upland.csv",
    "coast_predicted_impact_classes": "Q3_WUE_T_SPEI_coast_threshold_GAM_predicted_impact_classes_upland.csv",
    "coast_impact_thresholds": "Q3_WUE_T_SPEI_coast_threshold_GAM_impact_thresholds_10pct_upland.csv",
    
    # Threshold markers
    "gam_threshold_markers": "Q3_WUE_T_SPEI_GAM_impact_threshold_markers_5_10_20pct.csv",
    "gam_threshold_summary": "Q3_WUE_T_SPEI_GAM_threshold_summary_5_10_20pct.csv",
    "coast_threshold_markers": "Q3_WUE_T_SPEI_coast_threshold_GAM_threshold_markers_5_10_20pct_upland.csv",
    "coast_threshold_summary": "Q3_WUE_T_SPEI_coast_threshold_GAM_threshold_summary_5_10_20pct_upland.csv",
}

# All figure files generated by Q3 workflow
all_figure_files = {
    "fig_02": "Q3_plot_02_site_level_sensitivity_slopes.png",
    "fig_03": "Q3_plot_03_smooth_WUE_T_response_by_SPEI.png",
    "fig_04": "Q3_plot_04_WUE_T_SPEI_sensitivity_multipanel.png",
    "fig_06": "Q3_plot_06_WUE_T_selected_SPEI_timescales.png",
    "fig_07": "Q3_plot_07_most_sensitive_sites.png",
    "fig_09": "Q3_plot_09_all_system_sensitivity_heatmap.png",
    "fig_10": "Q3_plot_10_coast_specific_GAM_SPEI_thresholds_upland.png",
    "fig_11": "Q3_plot_11_coastline_grouped_site_sensitivity.png",
}

# Check Python CSV files
print("\nPython CSV files found:")
python_csv_available = {}
for name, filename in all_csv_files.items():
    filepath = os.path.join(python_output_dir, filename)
    exists = os.path.exists(filepath)
    python_csv_available[name] = exists
    status = "YES" if exists else "NO"
    print(f"  {name:40} {status}")

# Check Malone CSV files
print("\nMalone CSV files found:")
malone_csv_available = {}
for name, filename in all_csv_files.items():
    filepath = os.path.join(malone_output_dir, filename)
    exists = os.path.exists(filepath)
    malone_csv_available[name] = exists
    status = "YES" if exists else "NO"
    print(f"  {name:40} {status}")

# Check Python figure files
print("\nPython figure files found:")
python_fig_available = {}
for name, filename in all_figure_files.items():
    filepath = os.path.join(python_figure_dir, filename)
    exists = os.path.exists(filepath)
    python_fig_available[name] = exists
    status = "YES" if exists else "NO"
    print(f"  {name:15} {status}")

# ============================================================================
# COMPARE KEY METRICS
# ============================================================================

print("\n" + "-"*70)
print("STEP 2: Comparing key metrics")
print("-"*70)

all_results = {}
all_metrics_match = True

# Compare site slopes
if python_csv_available.get("site_slopes", False) and malone_csv_available.get("site_slopes", False):
    try:
        python_df = pd.read_csv(os.path.join(python_output_dir, all_csv_files["site_slopes"]))
        malone_df = pd.read_csv(os.path.join(malone_output_dir, all_csv_files["site_slopes"]))
        results, match = compare_dataframes(
            python_df, malone_df, "site_slopes",
            ['site_name', 'water_class', 'SPEI_timescale'],
            ['SPEI_slope', 'SPEI_cor', 'n_months']
        )
        all_results['site_slopes'] = results
        if not match:
            all_metrics_match = False
    except Exception as e:
        print(f"  ERROR comparing site_slopes: {e}")

# Compare model comparison
if python_csv_available.get("model_comparison", False) and malone_csv_available.get("model_comparison", False):
    try:
        python_df = pd.read_csv(os.path.join(python_output_dir, all_csv_files["model_comparison"]))
        malone_df = pd.read_csv(os.path.join(malone_output_dir, all_csv_files["model_comparison"]))
        results, match = compare_dataframes(
            python_df, malone_df, "model_comparison",
            ['model'],
            ['AIC', 'BIC', 'logLik', 'deviance_explained', 'adjusted_r_squared']
        )
        all_results['model_comparison'] = results
        if not match:
            all_metrics_match = False
    except Exception as e:
        print(f"  ERROR comparing model_comparison: {e}")

# Compare predictions
if python_csv_available.get("predictions", False) and malone_csv_available.get("predictions", False):
    try:
        python_df = pd.read_csv(os.path.join(python_output_dir, all_csv_files["predictions"]))
        malone_df = pd.read_csv(os.path.join(malone_output_dir, all_csv_files["predictions"]))
        results, match = compare_dataframes(
            python_df, malone_df, "predictions",
            ['SPEI_timescale', 'water_class', 'SPEI_value'],
            ['predicted_WUE_T', 'predicted_se']
        )
        all_results['predictions'] = results
        if not match:
            all_metrics_match = False
    except Exception as e:
        print(f"  ERROR comparing predictions: {e}")

# Compare site sensitivity rank
if python_csv_available.get("site_sensitivity_rank", False) and malone_csv_available.get("site_sensitivity_rank", False):
    try:
        python_df = pd.read_csv(os.path.join(python_output_dir, all_csv_files["site_sensitivity_rank"]))
        malone_df = pd.read_csv(os.path.join(malone_output_dir, all_csv_files["site_sensitivity_rank"]))
        results, match = compare_dataframes(
            python_df, malone_df, "site_sensitivity_rank",
            ['site_name', 'water_class', 'SPEI_timescale'],
            ['mean_abs_pct_change', 'max_abs_pct_change', 'n_months']
        )
        all_results['site_sensitivity_rank'] = results
        if not match:
            all_metrics_match = False
    except Exception as e:
        print(f"  ERROR comparing site_sensitivity_rank: {e}")

# Compare GAM threshold markers - FIXED: Include threshold_pct in merge key
if python_csv_available.get("gam_threshold_markers", False) and malone_csv_available.get("gam_threshold_markers", False):
    try:
        python_df = pd.read_csv(os.path.join(python_output_dir, all_csv_files["gam_threshold_markers"]))
        malone_df = pd.read_csv(os.path.join(malone_output_dir, all_csv_files["gam_threshold_markers"]))
        
        # Normalize threshold_pct in both dataframes
        python_df = normalize_threshold_pct(python_df)
        malone_df = normalize_threshold_pct(malone_df)
        
        results, match = compare_dataframes(
            python_df, malone_df, "gam_threshold_markers",
            ['SPEI_timescale', 'water_class', 'threshold_pct', 'impact_direction', 'anomaly_side'],
            ['SPEI_threshold', 'SPEI_threshold_lower', 'SPEI_threshold_upper', 'pct_change_threshold']
        )
        all_results['gam_threshold_markers'] = results
        if not match:
            all_metrics_match = False
    except Exception as e:
        print(f"  ERROR comparing gam_threshold_markers: {e}")

# Compare coast threshold markers - FIXED: Include threshold_pct in merge key
if python_csv_available.get("coast_threshold_markers", False) and malone_csv_available.get("coast_threshold_markers", False):
    try:
        python_df = pd.read_csv(os.path.join(python_output_dir, all_csv_files["coast_threshold_markers"]))
        malone_df = pd.read_csv(os.path.join(malone_output_dir, all_csv_files["coast_threshold_markers"]))
        
        # Normalize threshold_pct in both dataframes
        python_df = normalize_threshold_pct(python_df)
        malone_df = normalize_threshold_pct(malone_df)
        
        results, match = compare_dataframes(
            python_df, malone_df, "coast_threshold_markers",
            ['SPEI_timescale', 'coast_region', 'threshold_pct', 'impact_direction', 'anomaly_side'],
            ['SPEI_threshold', 'SPEI_threshold_lower', 'SPEI_threshold_upper', 'pct_change_threshold']
        )
        all_results['coast_threshold_markers'] = results
        if not match:
            all_metrics_match = False
    except Exception as e:
        print(f"  ERROR comparing coast_threshold_markers: {e}")

# Compare coast predictions
if python_csv_available.get("coast_predictions", False) and malone_csv_available.get("coast_predictions", False):
    try:
        python_df = pd.read_csv(os.path.join(python_output_dir, all_csv_files["coast_predictions"]))
        malone_df = pd.read_csv(os.path.join(malone_output_dir, all_csv_files["coast_predictions"]))
        results, match = compare_dataframes(
            python_df, malone_df, "coast_predictions",
            ['SPEI_timescale', 'coast_region', 'SPEI_value'],
            ['predicted_WUE_T', 'predicted_se']
        )
        all_results['coast_predictions'] = results
        if not match:
            all_metrics_match = False
    except Exception as e:
        print(f"  ERROR comparing coast_predictions: {e}")

# ============================================================================
# FIGURE FILE CHECK
# ============================================================================

print("\n" + "-"*70)
print("STEP 3: Checking figure files")
print("-"*70)

all_figures_exist = True
missing_figures = []
for name, filename in all_figure_files.items():
    filepath = os.path.join(python_figure_dir, filename)
    exists = os.path.exists(filepath)
    status = "YES" if exists else "NO"
    print(f"  {name:15} {status}")
    if not exists:
        all_figures_exist = False
        missing_figures.append(name)

# ============================================================================
# OVERALL CONCLUSION
# ============================================================================

print("\n" + "="*70)
print("OVERALL CONCLUSION")
print("="*70)

# Check CSV coverage
python_csv_missing = [name for name, exists in python_csv_available.items() if not exists]
malone_csv_missing = [name for name, exists in malone_csv_available.items() if not exists]

print(f"\nPython CSV files: {len([x for x in python_csv_available.values() if x])}/{len(all_csv_files)} found")
print(f"Malone CSV files: {len([x for x in malone_csv_available.values() if x])}/{len(all_csv_files)} found")

if python_csv_missing:
    print(f"\nWARNING: Python missing CSV files: {len(python_csv_missing)}")
    for name in python_csv_missing[:5]:
        print(f"    - {name}")

if malone_csv_missing:
    print(f"\nWARNING: Malone missing CSV files: {len(malone_csv_missing)}")
    for name in malone_csv_missing[:5]:
        print(f"    - {name}")

print(f"\nPython figure files: {len([x for x in python_fig_available.values() if x])}/{len(all_figure_files)} found")
if missing_figures:
    print(f"WARNING: Missing figures: {missing_figures}")

print("\nMetric comparison results:")
for name, results in all_results.items():
    if results:
        print(f"  {name}: {len(results)} columns compared")
        for col, max_diff in results.items():
            if max_diff <= 0.00001:
                status = "✓"
            elif max_diff <= 0.01:
                status = "✓"
            else:
                status = "✗"
            print(f"    {status} {col}: {max_diff:.8f}")

print("\n" + "-"*70)
if all_metrics_match and all_figures_exist and not python_csv_missing:
    print("\n[PASS] ALL METRICS MATCH! Python Q3 successfully replicates Malone R Q3.")
    print("        - All CSV files exist")
    print("        - All metrics match within tolerance")
    print("        - All figures exist")
elif not all_figures_exist:
    print("\n[WARNING] Figure files missing. Check Chunk 2 execution.")
else:
    print("\n[FAIL] Some metrics do not match or files are missing.")
    print("        Check the comparison results above.")

print("\n" + "="*70)
print("DIAGNOSTIC COMPLETE")
print("="*70)

# ============================================================================
# SAVE REPORT
# ============================================================================

report_lines = [
    "="*70,
    "Q3 DIAGNOSTIC REPORT: Python vs Malone R",
    "="*70,
    "",
    "File Availability:",
    "-"*40,
    "",
    "CSV Files:",
]

for name in all_csv_files.keys():
    py_exists = python_csv_available.get(name, False)
    ml_exists = malone_csv_available.get(name, False)
    report_lines.append(f"  {name:40} Python: {'YES' if py_exists else 'NO'}, Malone: {'YES' if ml_exists else 'NO'}")

report_lines.append("")
report_lines.append("Figure Files:")
for name in all_figure_files.keys():
    exists = python_fig_available.get(name, False)
    report_lines.append(f"  {name:15} {'YES' if exists else 'NO'}")

report_lines.append("")
report_lines.append("Comparison Results:")
report_lines.append("-"*40)

for name, results in all_results.items():
    report_lines.append(f"\n  {name}:")
    for col, max_diff in results.items():
        if max_diff <= 0.00001:
            status = "IDENTICAL"
        elif max_diff <= 0.01:
            status = "OK"
        else:
            status = "FAIL"
        report_lines.append(f"    [{status:8}] {col}: {max_diff:.8f}")

report_lines.append("")
report_lines.append("-"*40)
if all_metrics_match and all_figures_exist and not python_csv_missing:
    report_lines.append("RESULT: PASS - All metrics match!")
elif not all_figures_exist:
    report_lines.append("RESULT: WARNING - Figure files missing.")
else:
    report_lines.append("RESULT: FAIL - Some metrics do not match.")

report_lines.append("")
report_lines.append("="*70)

report_path = os.path.join(python_output_dir, "diagnostic_comparison_report.txt")
with open(report_path, 'w', encoding='utf-8') as f:
    f.write("\n".join(report_lines))

print(f"\nReport saved to: {report_path}")