# -*- coding: utf-8 -*-
"""
Chunk 1: Panel a – Drought exposure and positive WUE_T response during drought

Two maps that represent DIFFERENT quantities with DIFFERENT denominators
and are therefore NOT forced onto a common numerical scale:

  Left  — SPEI-3 drought exposure
          source: EDI_response_v2_dry_month_frequency_upland.nc
          quantity:
            100 x [ #(SPEI-3 <= -1 months) / #(all April-October months) ]
          scale:  0-35% (matches the data range; the exposure raster spans
                  roughly 9-33%, so a 0-35 scale reveals the spatial pattern)
          cmap:   YlOrBr (yellow -> brown; dry/exposure palette; matches
                  gold drought shading in Panel b)
          colorbar label:
            "Growing-season months with SPEI-3 <= -1 (%)"

  Right — Positive WUE_T response during drought
          source: EDI_response_v2_dry_freq_strong_increase_upland.nc
          quantity:
            100 x [ #(SPEI-3 <= -1 months with dWUE_T >= +5%)
                    / #(SPEI-3 <= -1 months) ]
          scale:  0-100% (this raster genuinely spans 0-100)
          cmap:   PuRd (pale pink -> dark purple-red), a distinct color
                  family so the response map is not confused with the
                  drought map
          colorbar label:
            "Dry months with WUE_T increase >= 5% (%)"

- Panel label "a)" placed at figure level (no collision with titles).
- No-data pixels are white/transparent; a faint nonwhite lowest color
  keeps valid 0% pixels visually distinguishable from missing cells.
- Layout, figure size, geographic extent, Alaska placement, coast labels,
  longitude/latitude axes, and output location are unchanged.
- Saves as 'EDI_panel_A_maps.png' in talib_publication at 900 dpi.

The two input rasters are already generated by 24-EDI_spatial.py.
No upstream scientific calculation is performed here.
"""

from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import netCDF4 as nc
import numpy as np

# ---------------------------------------------------------------------
# PATHS
# ---------------------------------------------------------------------
SPATIAL_DIR = Path(r"M:\Research\WUE_CUE\WUE_manuscript_version6\upscaling")
OUT_DIR = SPATIAL_DIR / "talib_publication"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Left: SPEI-3 drought exposure (all April-October months denominator)
exposure_path = SPATIAL_DIR / "EDI_response_v2_dry_month_frequency_upland.nc"
# Right: positive WUE_T response conditional on drought (dry-month denominator)
pos_path = SPATIAL_DIR / "EDI_response_v2_dry_freq_strong_increase_upland.nc"

OUT_FIG = OUT_DIR / "EDI_panel_A_maps.png"

# ---------------------------------------------------------------------
# COAST REGION LABEL POSITIONS (unchanged)
# ---------------------------------------------------------------------
REGION_LABEL_POS = {
    "AK Coast": (-167.0, 73.0, "Alaska"),
    "Pacific Coast": (-137.0, 41.0, "Pacific"),
    "Gulf Coast": (-101.0, 22.0, "Gulf"),
    "Atlantic Coast": (-82.0, 50.0, "Atlantic"),
}

# ---------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------
def read_raster(path):
    ds = nc.Dataset(path)
    lat = np.array(ds.variables["lat"][:])
    lon = np.array(ds.variables["lon"][:])
    var_name = [v for v in ds.variables if v not in ("lat", "lon")][0]
    arr = np.array(ds.variables[var_name][:], dtype=float)
    fill = getattr(ds.variables[var_name], "_FillValue", None)
    ds.close()
    if fill is not None:
        arr[arr == fill] = np.nan
    arr[~np.isfinite(arr)] = np.nan
    return lon, lat, arr


def style_map_axis(ax, label_fontsize=10):
    ax.set_xlim(-180, -60)
    ax.set_ylim(17, 77)
    ax.set_xlabel("Longitude", fontsize=label_fontsize)
    ax.set_ylabel("Latitude", fontsize=label_fontsize)
    ax.set_facecolor("white")
    ax.grid(False)
    for region, (x, y, label) in REGION_LABEL_POS.items():
        ax.text(
            x, y, label,
            ha="center", va="center",
            fontsize=8, fontweight="semibold", color="black",
        )


def print_diagnostics(name, arr):
    print(f"\n{name}")
    print("Valid pixels:", int(np.isfinite(arr).sum()))
    print("Min:", np.nanmin(arr) if np.isfinite(arr).any() else "NA")
    print("Max:", np.nanmax(arr) if np.isfinite(arr).any() else "NA")
    print("Pixels > 0%:", int(np.sum(np.isfinite(arr) & (arr > 0))))


# ---------------------------------------------------------------------
# READ DATA
# ---------------------------------------------------------------------
lon, lat, exposure = read_raster(exposure_path)
_, _, pos = read_raster(pos_path)

# ---------------------------------------------------------------------
# DIAGNOSTICS
# ---------------------------------------------------------------------
print_diagnostics("SPEI-3 DROUGHT EXPOSURE RASTER (left)", exposure)
print_diagnostics("POSITIVE DRY RESPONSE RASTER (right)", pos)

# ---------------------------------------------------------------------
# CREATE PANEL A
# ---------------------------------------------------------------------
fig, (ax_left, ax_right) = plt.subplots(
    1, 2, figsize=(7.4, 3.1), sharex=True, sharey=True
)
plt.subplots_adjust(wspace=0.04)

# Left: YlOrBr (yellow -> brown), with a faint nonwhite lowest color so
# valid 0% pixels remain distinguishable from no-data cells.
exposure_base = plt.get_cmap("YlOrBr")
exposure_cmap = exposure_base(np.linspace(0.03, 1.0, 256))
exposure_cmap = mcolors.LinearSegmentedColormap.from_list(
    "exposure_faintstart", exposure_cmap
)

# Right: PuRd (pale pink -> dark purple-red), a distinct color family so
# the response map is clearly not a second drought map. Faint nonwhite
# lowest color keeps valid 0% pixels distinguishable from no-data cells.
pos_base = plt.get_cmap("PuRd")
pos_cmap = pos_base(np.linspace(0.03, 1.0, 256))
pos_cmap = mcolors.LinearSegmentedColormap.from_list(
    "pos_faintstart", pos_cmap
)

exposure_cmap.set_bad((1, 1, 1, 0))
pos_cmap.set_bad((1, 1, 1, 0))

# DIFFERENT scales: exposure fits its own range (~9-33%), right spans 0-100.
im_left = ax_left.pcolormesh(
    lon, lat, exposure, cmap=exposure_cmap, vmin=0, vmax=35, shading="auto"
)
im_right = ax_right.pcolormesh(
    lon, lat, pos, cmap=pos_cmap, vmin=0, vmax=100, shading="auto"
)

style_map_axis(ax_left, label_fontsize=10)
style_map_axis(ax_right, label_fontsize=10)
ax_left.tick_params(labelsize=10)
ax_right.tick_params(labelsize=10)
ax_right.set_ylabel("")

# X-axis ticks: at least 5 ticks
ax_left.set_xticks(np.arange(-180, -30, 30))

# Titles
ax_left.set_title("SPEI-3 drought exposure",
                  fontweight="bold", fontsize=8)
ax_right.set_title("Positive WUE$_T$ response during drought",
                   fontweight="bold", fontsize=8)

# Colorbars with shorter labels that state the different denominators
cb_left = fig.colorbar(im_left, ax=ax_left, fraction=0.045, pad=0.02)
cb_right = fig.colorbar(im_right, ax=ax_right, fraction=0.045, pad=0.02)
cb_left.set_label("Growing-season months with SPEI-3 \u2264 -1 (%)",
                  fontsize=8, labelpad=2)
cb_right.set_label("Dry months with WUE$_T$ increase \u22655% (%)",
                   fontsize=8, labelpad=2)
cb_left.ax.tick_params(labelsize=8)
cb_right.ax.tick_params(labelsize=8)

# Panel label at figure level (no collision with titles)
fig.text(0.01, 0.98, "a)", fontsize=11, fontweight="bold",
         va="top", ha="left")

fig.tight_layout()

# ---------------------------------------------------------------------
# SAVE AND DISPLAY
# ---------------------------------------------------------------------
fig.savefig(OUT_FIG, dpi=900, bbox_inches="tight", facecolor="white")
print(f"\nPanel A saved to: {OUT_FIG}")

plt.show(block=True)
print("Panel A displayed.")