# Q3_reference_condition_sensitivity_diagnostic.py (DYNAMIC INTERPRETATION, CLEANUP, OUTPUT CHECK)
# -----------------------------------------------------------------------------
# DIAGNOSTIC FLAGS
# -----------------------------------------------------------------------------
SAVE_CSV = True
SAVE_FIGURES = False
SAVE_LOG = False
# -----------------------------------------------------------------------------

import os
import subprocess
import sys
import shutil
import pandas as pd
import numpy as np

print("=" * 70)
print("Q3 REFERENCE-CONDITION SENSITIVITY DIAGNOSTIC")
print("=" * 70)

# -----------------------------------------------------------------------------
# PATHS
# -----------------------------------------------------------------------------
diagnostic_dir = r"M:\Research\WUE_CUE\Water_WUE\manuscripts_Analysis\Q3\sensitivity_conditions"
output_dir = r"M:\Research\WUE_CUE\WUE_manuscript_version6\Q3\Q3_WUE_T_SPEI_sensitivity_outputs"
results_dir = os.path.join(output_dir, "sensitivity_conditions_results")

data_long_path = os.path.join(output_dir, "Q3_WUE_T_SPEI_model_data_long.csv")
model_rds_path = os.path.join(output_dir, "Q3_WUE_T_SPEI_coast_threshold_gam_model.rds")
smooth_terms_path = os.path.join(output_dir, "Q3_WUE_T_SPEI_coast_threshold_GAM_smooth_terms.csv")

if not os.path.exists(model_rds_path):
    raise FileNotFoundError(f"Model RDS not found: {model_rds_path}")
if not os.path.exists(data_long_path):
    raise FileNotFoundError(f"Data long CSV not found: {data_long_path}")

print(f"Input model:  {model_rds_path}")
print(f"Input data:   {data_long_path}")

os.makedirs(diagnostic_dir, exist_ok=True)
os.makedirs(results_dir, exist_ok=True)

# -----------------------------------------------------------------------------
# CLEANUP: remove old sensitivity CSVs before running
# -----------------------------------------------------------------------------
expected_outputs = [
    "prediction_curves_all_reference_conditions.csv",
    "threshold_summary_all_reference_conditions.csv",
    "threshold_sensitivity_summary.csv",
    "response_magnitude_all_reference_conditions.csv",
    "reference_condition_sensitivity_summary.csv",
    "observed_support_metadata.csv"
]
print("\nCleaning old sensitivity CSVs from results_dir...")
for fname in expected_outputs:
    fpath = os.path.join(results_dir, fname)
    if os.path.exists(fpath):
        os.remove(fpath)
        print(f"  Removed: {fname}")

# -----------------------------------------------------------------------------
# CONVERT PATHS TO R‑SAFE FORWARD SLASHES
# -----------------------------------------------------------------------------
output_dir_r = output_dir.replace("\\", "/")
results_dir_r = results_dir.replace("\\", "/")
data_long_path_r = data_long_path.replace("\\", "/")
model_rds_path_r = model_rds_path.replace("\\", "/")
diagnostic_dir_r = diagnostic_dir.replace("\\", "/")

# -----------------------------------------------------------------------------
# BUILD THE R SCRIPT (unchanged core calculations)
# -----------------------------------------------------------------------------
r_script_content = f'''
# Diagnostic R script (generated by Python)
library(mgcv)
library(dplyr)
library(tidyr)

output_dir <- "{output_dir_r}"
results_dir <- "{results_dir_r}"
data_long_path <- "{data_long_path_r}"
model_rds_path <- "{model_rds_path_r}"

cat("\\nLoading model...\\n")
smooth_coast_model <- readRDS(model_rds_path)
cat("  Model loaded.\\n")
cat("  Model formula:\\n")
print(formula(smooth_coast_model))

cat("\\nLoading data...\\n")
data <- read.csv(data_long_path)
cat("  Data loaded. Rows:", nrow(data), "\\n")

# Set factor levels exactly as in original workflow
coast_levels <- c("Atlantic Coast", "Pacific Coast", "Gulf Coast", "AK Coast")
water_levels <- c("Upland", "Freshwater", "Saline")
spei_levels <- c("SPEI_1", "SPEI_3", "SPEI_6", "SPEI_12", "SPEI_24", "SPEI_36", "SPEI_48")
month_levels <- as.character(1:12)

data$coast_region <- factor(data$coast_region, levels = coast_levels)
data$water_class <- factor(data$water_class, levels = water_levels)
data$SPEI_timescale <- factor(data$SPEI_timescale, levels = spei_levels)
data$month_f <- factor(data$month_f, levels = month_levels)
data$site_name <- factor(data$site_name)

cat("  Factor levels set.\\n")

# Growing-season months (4-10, fallback to 6-8)
months_to_use <- intersect(4:10, as.numeric(levels(data$month_f)))
if (length(months_to_use) == 0) months_to_use <- intersect(6:8, as.numeric(levels(data$month_f)))
month_f_levels <- factor(months_to_use, levels = month_levels)
cat("  Months used:", as.character(month_f_levels), "\\n")

spei_lower <- max(-3, min(data$SPEI_value, na.rm = TRUE))
spei_upper <- min(3, max(data$SPEI_value, na.rm = TRUE))

spei_seq <- seq(
    spei_lower,
    spei_upper,
    length.out = 160
)

cat("  SPEI range:", round(min(spei_seq), 3), "to", round(max(spei_seq), 3), "\n")

site_ref <- levels(data$site_name)[1]

cat("\\nBuilding prediction grid...\\n")
grid <- expand.grid(
    coast_region = coast_levels,
    water_class = water_levels,
    month_f = month_f_levels,
    SPEI_timescale = spei_levels,
    SPEI_value = spei_seq,
    site_name = site_ref,
    stringsAsFactors = FALSE
)

grid$coast_region <- factor(grid$coast_region, levels = coast_levels)
grid$water_class <- factor(grid$water_class, levels = water_levels)
grid$SPEI_timescale <- factor(grid$SPEI_timescale, levels = spei_levels)
grid$month_f <- factor(grid$month_f, levels = month_levels)
grid$site_name <- factor(grid$site_name, levels = levels(data$site_name))

data$spei_coast <- interaction(data$SPEI_timescale, data$coast_region, sep = "__", drop = TRUE)
grid$spei_coast <- interaction(grid$SPEI_timescale, grid$coast_region, sep = "__", drop = TRUE)
grid$spei_coast <- factor(grid$spei_coast, levels = levels(data$spei_coast))

cat("  Grid size:", nrow(grid), "rows\\n")

# Predict (exclude site random effect)
cat("\\nPredicting from model...\\n")
pred <- predict(smooth_coast_model, newdata = grid, type = "link",
                se.fit = TRUE, exclude = "s(site_name)")
grid$predicted_WUE_T <- as.numeric(pred$fit)
grid$predicted_se <- as.numeric(pred$se.fit)
grid$predicted_lower <- grid$predicted_WUE_T - 1.96 * grid$predicted_se
grid$predicted_upper <- grid$predicted_WUE_T + 1.96 * grid$predicted_se
cat("  Predictions done.\\n")

# Near-normal baselines
baselines <- grid %>%
    filter(SPEI_value >= -1 & SPEI_value <= 1) %>%
    group_by(coast_region, water_class, month_f, SPEI_timescale) %>%
    summarise(predicted_near_normal_WUE_T = mean(predicted_WUE_T, na.rm = TRUE), .groups = "drop")

grid_with_baseline <- left_join(grid, baselines,
                                by = c("coast_region", "water_class", "month_f", "SPEI_timescale"))

grid_with_baseline$predicted_pct_change <-
    100 * (grid_with_baseline$predicted_WUE_T - grid_with_baseline$predicted_near_normal_WUE_T) /
    grid_with_baseline$predicted_near_normal_WUE_T

grid_with_baseline$predicted_lower_pct <-
    100 * (grid_with_baseline$predicted_lower - grid_with_baseline$predicted_near_normal_WUE_T) /
    grid_with_baseline$predicted_near_normal_WUE_T

grid_with_baseline$predicted_upper_pct <-
    100 * (grid_with_baseline$predicted_upper - grid_with_baseline$predicted_near_normal_WUE_T) /
    grid_with_baseline$predicted_near_normal_WUE_T

cat("  Percent changes computed.\\n")

# -------------------------------------------------------------------------
# THRESHOLD DETECTION FUNCTION
# -------------------------------------------------------------------------
find_spei_threshold <- function(group_data, pct_column, threshold_pct,
                                anomaly_side, impact_direction) {{
    pct_values <- group_data[[pct_column]]
    if (anomaly_side == "dry") side_filter <- group_data$SPEI_value < -1
    else side_filter <- group_data$SPEI_value > 1
    if (impact_direction == "decrease") direction_filter <- pct_values <= -threshold_pct
    else direction_filter <- pct_values >= threshold_pct
    threshold_values <- group_data$SPEI_value[side_filter & direction_filter]
    if (length(threshold_values) == 0) return(NA_real_)
    if (anomaly_side == "dry") return(max(threshold_values, na.rm = TRUE))
    else return(min(threshold_values, na.rm = TRUE))
}}

# -------------------------------------------------------------------------
# COMPUTE THRESHOLDS FOR ALL COMBINATIONS – with corrected rule
# -------------------------------------------------------------------------
cat("\\nComputing thresholds...\\n")

all_threshold_combos <- expand.grid(
    coast_region = coast_levels,
    water_class = water_levels,
    month_f = month_f_levels,
    SPEI_timescale = spei_levels,
    threshold_pct = c(5, 10, 20),
    anomaly_side = c("dry", "wet"),
    impact_direction = c("decrease", "increase"),
    stringsAsFactors = FALSE
)

all_threshold_combos$threshold_detected <- FALSE
all_threshold_combos$SPEI_threshold <- NA_real_
all_threshold_combos$SPEI_threshold_lower <- NA_real_
all_threshold_combos$SPEI_threshold_upper <- NA_real_

groups <- split(grid_with_baseline,
                list(grid_with_baseline$coast_region,
                     grid_with_baseline$water_class,
                     grid_with_baseline$month_f,
                     grid_with_baseline$SPEI_timescale),
                drop = TRUE)

for (grp in groups) {{
    if (nrow(grp) == 0) next
    coast <- as.character(grp$coast_region[1])
    water <- as.character(grp$water_class[1])
    month <- as.character(grp$month_f[1])
    timescale <- as.character(grp$SPEI_timescale[1])
    
    for (tp in c(5, 10, 20)) {{
        for (anom in c("dry", "wet")) {{
            for (dir in c("decrease", "increase")) {{
                idx <- which(all_threshold_combos$coast_region == coast &
                             all_threshold_combos$water_class == water &
                             all_threshold_combos$month_f == month &
                             all_threshold_combos$SPEI_timescale == timescale &
                             all_threshold_combos$threshold_pct == tp &
                             all_threshold_combos$anomaly_side == anom &
                             all_threshold_combos$impact_direction == dir)
                if (length(idx) == 0) next
                
                thresh_mean <- find_spei_threshold(grp, "predicted_pct_change", tp, anom, dir)
                thresh_lower <- find_spei_threshold(grp, "predicted_lower_pct", tp, anom, dir)
                thresh_upper <- find_spei_threshold(grp, "predicted_upper_pct", tp, anom, dir)
                
                # --- CORRECTED RULE: only mean curve crossing counts as detected ---
                if (!is.na(thresh_mean)) {{
                    all_threshold_combos$threshold_detected[idx] <- TRUE
                    all_threshold_combos$SPEI_threshold[idx] <- thresh_mean
                    
                    thresh_range <- c(thresh_mean, thresh_lower, thresh_upper)
                    thresh_range <- thresh_range[!is.na(thresh_range)]
                    
                    all_threshold_combos$SPEI_threshold_lower[idx] <- min(thresh_range)
                    all_threshold_combos$SPEI_threshold_upper[idx] <- max(thresh_range)
                }}
                # --- end correction ---
            }}
        }}
    }}
}}

cat("  Thresholds computed. Total combinations:", nrow(all_threshold_combos), "\\n")

# -------------------------------------------------------------------------
# SAVE CSVs
# -------------------------------------------------------------------------
prediction_curves <- grid_with_baseline %>%
    select(coast_region, water_class, month_f, SPEI_timescale, SPEI_value,
           predicted_WUE_T, predicted_lower, predicted_upper,
           predicted_near_normal_WUE_T, predicted_pct_change,
           predicted_lower_pct, predicted_upper_pct)
write.csv(prediction_curves, file.path(results_dir, "prediction_curves_all_reference_conditions.csv"), row.names = FALSE)

threshold_summary_all <- all_threshold_combos %>%
    select(coast_region, water_class, month_f, SPEI_timescale,
           threshold_pct, anomaly_side, impact_direction,
           threshold_detected, SPEI_threshold,
           SPEI_threshold_lower, SPEI_threshold_upper)
write.csv(threshold_summary_all, file.path(results_dir, "threshold_summary_all_reference_conditions.csv"), row.names = FALSE)

threshold_sensitivity <- threshold_summary_all %>%
    group_by(coast_region, water_class, SPEI_timescale,
             threshold_pct, anomaly_side, impact_direction) %>%
    summarise(
        n_months_total = n_distinct(month_f),
        n_months_with_threshold = sum(threshold_detected, na.rm = TRUE),
        mean_SPEI_threshold = ifelse(sum(threshold_detected) > 0,
                                     mean(SPEI_threshold, na.rm = TRUE), NA_real_),
        sd_SPEI_threshold = ifelse(sum(threshold_detected) > 0,
                                   sd(SPEI_threshold, na.rm = TRUE), NA_real_),
        min_SPEI_threshold = ifelse(sum(threshold_detected) > 0,
                                    min(SPEI_threshold, na.rm = TRUE), NA_real_),
        max_SPEI_threshold = ifelse(sum(threshold_detected) > 0,
                                    max(SPEI_threshold, na.rm = TRUE), NA_real_),
        threshold_range = ifelse(sum(threshold_detected) > 0,
                                 paste(format(min(SPEI_threshold, na.rm=TRUE), digits=3),
                                       "to",
                                       format(max(SPEI_threshold, na.rm=TRUE), digits=3)),
                                 NA_character_),
        .groups = "drop"
    )
write.csv(threshold_sensitivity, file.path(results_dir, "threshold_sensitivity_summary.csv"), row.names = FALSE)

response_magnitude <- grid_with_baseline %>%
    group_by(coast_region, water_class, month_f, SPEI_timescale) %>%
    summarise(
        max_abs_pct_change = max(abs(predicted_pct_change), na.rm = TRUE),
        min_signed_pct_change = min(predicted_pct_change, na.rm = TRUE),
        max_signed_pct_change = max(predicted_pct_change, na.rm = TRUE),
        max_abs_dry_pct_change = max(abs(predicted_pct_change[SPEI_value < -1]), na.rm = TRUE),
        max_abs_wet_pct_change = max(abs(predicted_pct_change[SPEI_value > 1]), na.rm = TRUE),
        .groups = "drop"
    )
write.csv(response_magnitude, file.path(results_dir, "response_magnitude_all_reference_conditions.csv"), row.names = FALSE)

sensitivity_summary <- response_magnitude %>%
    group_by(coast_region, water_class, SPEI_timescale) %>%
    summarise(
        mean_max_abs_pct_change = mean(max_abs_pct_change, na.rm = TRUE),
        min_max_abs_pct_change = min(max_abs_pct_change, na.rm = TRUE),
        max_max_abs_pct_change = max(max_abs_pct_change, na.rm = TRUE),
        best_month = month_f[which.max(max_abs_pct_change)][1],
        .groups = "drop"
    )
write.csv(sensitivity_summary, file.path(results_dir, "reference_condition_sensitivity_summary.csv"), row.names = FALSE)

support_observed <- data %>%
    group_by(coast_region, water_class) %>%
    summarise(
        n_sites = n_distinct(site_name),
        n_site_months = n_distinct(paste(site_name, Year, month, sep = "_")),
        n_long_rows = n(),
        year_min = min(Year, na.rm = TRUE),
        year_max = max(Year, na.rm = TRUE),
        .groups = "drop"
    )

full_grid <- expand.grid(
    coast_region = coast_levels,
    water_class = water_levels,
    stringsAsFactors = FALSE
)

support <- full_grid %>%
    left_join(support_observed, by = c("coast_region", "water_class")) %>%
    mutate(
        n_sites = ifelse(is.na(n_sites), 0, n_sites),
        n_site_months = ifelse(is.na(n_site_months), 0, n_site_months),
        n_long_rows = ifelse(is.na(n_long_rows), 0, n_long_rows),
        year_min = ifelse(is.na(year_min), NA_integer_, year_min),
        year_max = ifelse(is.na(year_max), NA_integer_, year_max),
        observed_support_note = case_when(
            n_sites == 0 ~ "no matching observed coast-ecosystem combination",
            n_sites >= 5 ~ "observed in fitting data",
            n_sites >= 2 ~ "limited observed representation",
            TRUE ~ "very sparse observed representation"
        )
    )
write.csv(support, file.path(results_dir, "observed_support_metadata.csv"), row.names = FALSE)

cat("\\nCSVs saved to:", results_dir, "\\n")
'''

# -----------------------------------------------------------------------------
# WRITE AND RUN THE R SCRIPT
# -----------------------------------------------------------------------------
r_script_path = os.path.join(diagnostic_dir, "diagnostic.R")
with open(r_script_path, 'w', encoding='utf-8') as f:
    f.write(r_script_content)

rscript_exe = shutil.which("Rscript")
if rscript_exe is None:
    possible_path = r"C:\Program Files\R\R-4.4.2\bin\x64\Rscript.exe"
    if os.path.exists(possible_path):
        rscript_exe = possible_path
    else:
        raise RuntimeError("Rscript not found.")

print(f"\nRunning R script: {r_script_path}")
result = subprocess.run([rscript_exe, r_script_path], capture_output=True, text=True)

if result.returncode != 0:
    print("\nERROR: R script failed.")
    print(result.stderr)
    sys.exit(1)

print(result.stdout)

# -----------------------------------------------------------------------------
# REQUIRED-OUTPUT CHECK
# -----------------------------------------------------------------------------
print("\nChecking for required sensitivity CSVs...")
missing = []
for fname in expected_outputs:
    fpath = os.path.join(results_dir, fname)
    if not os.path.exists(fpath):
        missing.append(fname)
if missing:
    raise FileNotFoundError(
        "Missing required sensitivity CSVs:\n" + "\n".join(missing)
    )
print("All six sensitivity CSVs are present.")

# -----------------------------------------------------------------------------
# DYNAMIC INTERPRETATION (based on smooth terms CSV)
# -----------------------------------------------------------------------------
print("\n=== TOP 10 STRONGEST MODEL-PREDICTED REFERENCE CONDITIONS ===")
# We need to reload the CSVs to print summaries.
# Since we have the R output printed above, we could also parse the CSVs.
# For consistency, we load the CSV files we just wrote.
pred_curves = pd.read_csv(os.path.join(results_dir, "prediction_curves_all_reference_conditions.csv"))
thresh_all = pd.read_csv(os.path.join(results_dir, "threshold_summary_all_reference_conditions.csv"))
response_magnitude = pd.read_csv(os.path.join(results_dir, "response_magnitude_all_reference_conditions.csv"))
sensitivity_summary = pd.read_csv(os.path.join(results_dir, "reference_condition_sensitivity_summary.csv"))
threshold_sensitivity = pd.read_csv(os.path.join(results_dir, "threshold_sensitivity_summary.csv"))

top10_response = response_magnitude.sort_values("max_abs_pct_change", ascending=False).head(10)
print(top10_response.to_string())

print("\n=== TOP 10 COAST × ECOSYSTEM × SPEI TIMESCALE COMBINATIONS ===")
top10_sensitivity = sensitivity_summary.sort_values("mean_max_abs_pct_change", ascending=False).head(10)
print(top10_sensitivity.to_string())

print("\n=== THRESHOLD STABILITY (combinations with thresholds across most months) ===")
threshold_stability = threshold_sensitivity[
    threshold_sensitivity["n_months_with_threshold"] >= 6
].sort_values(["n_months_with_threshold", "mean_SPEI_threshold"], ascending=[False, False])
print(threshold_stability.to_string())

# -----------------------------------------------------------------------------
# DYNAMIC SMOOTH EXTRACTION
# -----------------------------------------------------------------------------
print("\n=== DYNAMICALLY IDENTIFIED STRONGEST COAST-SPECIFIC SMOOTH ===")
if os.path.exists(smooth_terms_path):
    smooth_df = pd.read_csv(smooth_terms_path)
    # Find p-value column
    p_col = "p.value" if "p.value" in smooth_df.columns else "p-value" if "p-value" in smooth_df.columns else None
    if p_col is not None:
        # Filter coast smooths (spei_coast) and exclude site random effect
        coast_smooths = smooth_df[
            smooth_df["smooth_term"].str.contains("spei_coast", na=False) &
            ~smooth_df["smooth_term"].str.contains("site_name", na=False)
        ].copy()
        sig_smooths = coast_smooths[coast_smooths[p_col] < 0.05]
        if not sig_smooths.empty:
            # Identify strongest by F statistic
            focus_row = sig_smooths.loc[sig_smooths["F"].idxmax()]
            term = focus_row["smooth_term"]
            # Parse coast and timescale
            # Example: "s(SPEI_value):spei_coastSPEI_3__Pacific Coast"
            parts = term.split("__")
            if len(parts) == 2:
                focus_coast = parts[1].strip()
                timescale_part = parts[0].replace("s(SPEI_value):spei_coast", "").strip()
                focus_timescale = timescale_part
            else:
                focus_coast = "unknown"
                focus_timescale = "unknown"
            focus_F = focus_row["F"]
            focus_p = focus_row[p_col]
            print(f"  Strongest significant coast smooth: {focus_coast} at {focus_timescale}")
            print(f"    F = {focus_F:.2f}, p = {focus_p:.3f}")
            # Check if Gulf Coast appears among significant smooths
            gulf_sig = sig_smooths[sig_smooths["smooth_term"].str.contains("Gulf Coast", na=False)]
            if not gulf_sig.empty:
                print("  Gulf Coast has significant smooth terms (see above).")
            else:
                print("  Gulf Coast has no significant smooth terms (p < 0.05).")
        else:
            print("  No significant coast-specific smooth (p < 0.05) found.")
            focus_coast = "none"
            focus_timescale = "none"
    else:
        print("  No p-value column found in smooth terms CSV.")
        focus_coast = "unknown"
        focus_timescale = "unknown"
else:
    print("  Smooth terms CSV not found.")
    focus_coast = "unknown"
    focus_timescale = "unknown"

# -----------------------------------------------------------------------------
# MAIN INTERPRETATION (dynamic, no hardcoded Gulf)
# -----------------------------------------------------------------------------
print("\n=== MAIN DIAGNOSTIC INTERPRETATION ===")
print("The sensitivity analysis used a full prediction grid across all coast × ecosystem,")
print("growing-season month, and SPEI timescale combinations to evaluate model-predicted")
print("WUE_T response magnitude and threshold location.\n")

if focus_coast not in ["none", "unknown"]:
    print(f"The strongest coast-specific smooth was concentrated in {focus_coast} at {focus_timescale},")
    print("with the largest magnitudes occurring under various reference ecosystem classes.")
else:
    print("No coast-specific smooth was significant at p < 0.05, suggesting that coastlines")
    print("did not strongly differentiate WUE_T responses in this model.\n")

print("\nTop responses were dominated by combinations with the highest mean absolute")
print("percent changes, as shown in the tables above. Threshold stability (≥6 months)")
print("occurred mainly for dry-decrease thresholds in certain coast × ecosystem × SPEI")
print("combinations, but threshold directions were not uniform.\n")

print("Caution: Freshwater, Saline, and Upland differences in this sensitivity diagnostic")
print("are reference-condition predictions from the coast-threshold GAM, not independent")
print("ecosystem-specific smooth tests. They reflect model behavior under different")
print("reference ecosystem classes, not observed ecosystem-specific responses.\n")

print(f"Diagnostic completed successfully. Sensitivity CSVs were written to: {results_dir}")
print("These files can now be used by Q3_sensitivity_four_panel_figure.py.")